import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react"
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Mirac.eth Blog",
    template: "%s | Mirac.eth Blog"
  },
  description: "Generated by create next app",
};

export default function RootLayout({ session, children }) {
  return (
    <html lang="en">
          <SessionProvider session={session}>
      <body className={inter.className}>
          <Navbar />
          {children}</body>
        </SessionProvider>
    </html>
  );
}